### ISSUE TITLE
Using bump on a file that has non ascii characters, bump fails and erases the whole file

### ISSUE THREAD

**Issue by george-silva** [marksteve/bump#12]
Hello!

I just tried bump. When there is a proper setup.py file, but with non-ascii characters (the encoding is declared on top of the file!), bump spits an error and overwrites the file with nothing.

Here's the traceback.

```python
george@winterfell ~/projetos/corporativo/django-comum $ bump setup.py 
setup.py: 1.0.1 => 1.0.2
Is this ok? y/n y
Traceback (most recent call last):
  File "/usr/local/bin/bump", line 9, in <module>
    load_entry_point('bump==0.3.0', 'console_scripts', 'bump')()
  File "/usr/local/lib/python2.7/dist-packages/bump.py", line 123, in main
    bumped_version_string + content[match['match'].end(1):])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 138-139: ordinal not in range(128)
```

**Comment by marksteve** [comment]
Hi @george-silva! I don't maintain bump anymore. Try this instead: https://github.com/rstacruz/bump-cli
